// <auto-generated />
namespace Brew.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ff));
        
        string IMigrationMetadata.Id
        {
            get { return "201304040227079_ff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
